# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"

  config.vm.box_check_update = false

  config.vm.network "public_network"

  config.vm.synced_folder "./packer", "/home/vagrant/packer"

  config.vm.provision "shell", path: "bootstrap.sh"
end
